### ISSUE TITLE
Feed/Home UI - Create information card

### ISSUE THREAD

**Issue by caroltr** [FightPandemics/FightPandemics-android#23]
**Description:**
Create the UI that displays all information from All, Offers, or Requests views.

Follow the design below:
![Captura de Tela 2020-05-25 às 13 24 07](https://user-images.githubusercontent.com/13593253/82830044-0f25ce00-9e8b-11ea-846f-55a39f6b25d4.png)

**Comment by devarshjoshi** [comment]
closing this ticket. related: https://github.com/FightPandemics/FightPandemics-android/issues/40
